const assert = require('node:assert/strict');
const fs = require('node:fs');
const { JSDOM } = require('jsdom');
const I = require('../couple-invite.js');
const token = 'a'.repeat(64);
const url = I.link('https://ledger.example/app/?unrelated=1#old', token);
assert.equal(url, 'https://ledger.example/app/#couple-invite=' + token);
assert.equal(I.parse(url), token);
assert.equal(I.parse('https://ledger.example/#couple-invite=short'), null);
assert.equal(I.parse('https://ledger.example/#couple-invite=' + token + '&other=1'), null);
assert.throws(() => I.link('javascript:alert(1)', token));
const dom = new JSDOM('<!doctype html>', { url, runScripts: 'outside-only' });
dom.window.eval(fs.readFileSync(require.resolve('../couple-invite.js'), 'utf8'));
assert.equal(dom.window.location.href, 'https://ledger.example/app/');
assert.equal(dom.window.LedgerCoupleInvitation.pending, token);
assert.equal(dom.window.localStorage.length, 0);
assert.equal(dom.window.sessionStorage.length, 0);
dom.window.LedgerCoupleInvitation.clear();
assert.equal(dom.window.LedgerCoupleInvitation.pending, null);
const html = fs.readFileSync(require.resolve('../index.html'), 'utf8');
assert.ok(html.indexOf('src="couple-invite.js"') < html.indexOf('src="posthog'));
dom.window.close();
console.log('[OK] private invitation links: format, early URL sanitization, no persistence, explicit consumption');
